//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.SpriteEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.SpriteEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ARUTE_SHP {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOKO_SHP {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EFF1 {
            get {
                object obj = ResourceManager.GetObject("EFF1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EFF2 {
            get {
                object obj = ResourceManager.GetObject("EFF2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANZEN_SHP {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MON {
            get {
                object obj = ResourceManager.GetObject("MON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OTHER {
            get {
                object obj = ResourceManager.GetObject("OTHER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] resources_tar {
            get {
                object obj = ResourceManager.GetObject("resources_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TYPE1_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TYPE2_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WEP1 {
            get {
                object obj = ResourceManager.GetObject("WEP1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WEP2 {
            get {
                object obj = ResourceManager.GetObject("WEP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
