//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LionEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Artefacts {
            get {
                return ResourceManager.GetString("Artefacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Feats {
            get {
                return ResourceManager.GetString("Feats", resourceCulture);
            }
        }
        
        internal static byte[] FFTSaveHook {
            get {
                object obj = ResourceManager.GetObject("FFTSaveHook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainJobBasedOnSprite {
            get {
                return ResourceManager.GetString("MainJobBasedOnSprite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RandomNames {
            get {
                return ResourceManager.GetString("RandomNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecondaryAction {
            get {
                return ResourceManager.GetString("SecondaryAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sprites {
            get {
                return ResourceManager.GetString("Sprites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of LionEditor.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Wonders {
            get {
                return ResourceManager.GetString("Wonders", resourceCulture);
            }
        }
    }
}
