//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LionEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Abilities&gt;
        ///  &lt;Ability value=&quot;0&quot;&gt;&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;1&quot;&gt;Cure&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;2&quot;&gt;Cura&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;3&quot;&gt;Curaga&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;4&quot;&gt;Curaja&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;5&quot;&gt;Raise&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;6&quot;&gt;Arise&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;7&quot;&gt;Reraise&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;8&quot;&gt;Regen&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;9&quot;&gt;Protect&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;10&quot;&gt;Protectja&lt;/Ability&gt;
        ///  &lt;Ability value=&quot;11&quot;&gt;Shell&lt;/Ability [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Classes&gt;
        ///  &lt;Class&gt;
        ///    &lt;byte&gt;01&lt;/byte&gt;
        ///    &lt;skillset&gt;19&lt;/skillset&gt;
        ///    &lt;sprite&gt;Ramza, chapter 1&lt;/sprite&gt;
        ///    &lt;name&gt;Squire&lt;/name&gt;
        ///    &lt;command&gt;Mettle&lt;/command&gt;
        ///    &lt;hpm&gt;125&lt;/hpm&gt;
        ///    &lt;mpm&gt;105&lt;/mpm&gt;
        ///    &lt;spm&gt;107&lt;/spm&gt;
        ///    &lt;pam&gt;111&lt;/pam&gt;
        ///    &lt;mam&gt;102&lt;/mam&gt;
        ///    &lt;move&gt;4&lt;/move&gt;
        ///    &lt;cev&gt;10&lt;/cev&gt;
        ///    &lt;hpc&gt;11&lt;/hpc&gt;
        ///    &lt;mpc&gt;11&lt;/mpc&gt;
        ///    &lt;spc&gt;95&lt;/spc&gt;
        ///    &lt;pac&gt;50&lt;/pac&gt;
        ///    &lt;mac&gt;48&lt;/mac&gt;
        ///    &lt;jump&gt;3&lt;/jump&gt;
        ///    &lt;type&gt;Special&lt;/type&gt;
        ///  &lt;/Class&gt;
        ///  &lt;Class&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///  &lt;Item offset=&quot;255&quot; type=&quot;None&quot; subtype=&quot;None&quot;&gt;Nothing&lt;/Item&gt;
        ///  &lt;Item offset=&quot;0&quot; type=&quot;None&quot; subtype=&quot;None&quot;&gt;Nothing&lt;/Item&gt;
        ///  &lt;Item offset=&quot;1&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Dagger&lt;/Item&gt;
        ///  &lt;Item offset=&quot;2&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Mythril Knife&lt;/Item&gt;
        ///  &lt;Item offset=&quot;3&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Blind Knife&lt;/Item&gt;
        ///  &lt;Item offset=&quot;4&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Mage Masher&lt;/Item&gt;
        ///  &lt;Item offset=&quot;5&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Platinum Dagger&lt;/Item&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;JobsWithAbilities&gt;
        ///  &lt;Generic&gt;
        ///    &lt;Job name=&quot;Squire&quot;&gt;
        ///      &lt;!-- This is the byte to set for --&gt;
        ///      &lt;bytes&gt;05&lt;/bytes&gt;
        ///      &lt;command&gt;Fundaments&lt;/command&gt;
        ///      &lt;action&gt;
        ///        &lt;skill&gt;Focus&lt;/skill&gt;
        ///        &lt;skill&gt;Rush&lt;/skill&gt;
        ///        &lt;skill&gt;Stone&lt;/skill&gt;
        ///        &lt;skill&gt;Salve&lt;/skill&gt;
        ///        &lt;skill&gt;Tailwind&lt;/skill&gt;
        ///        &lt;skill&gt;Chant&lt;/skill&gt;
        ///      &lt;/action&gt;
        ///      &lt;reaction&gt;
        ///        &lt;skill&gt;Counter Tackle&lt;/skill&gt;
        ///      &lt;/reaction&gt;
        ///      &lt;support&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JobsWithAbilities {
            get {
                return ResourceManager.GetString("JobsWithAbilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SecondaryActions&gt;
        ///  &lt;SecondaryAction byte=&quot;00&quot;&gt;Nothing&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;01&quot;&gt;Attack&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;02&quot;&gt;Defend&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;03&quot;&gt;Reequip&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;04&quot;&gt;Flee&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;05&quot;&gt;Fundaments&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;06&quot;&gt;Items&lt;/SecondaryAction&gt;
        ///  &lt;SecondaryAction byte=&quot;07&quot;&gt;Arts of War&lt;/SecondaryAction&gt;
        ///  &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SecondaryAction {
            get {
                return ResourceManager.GetString("SecondaryAction", resourceCulture);
            }
        }
    }
}
