//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LionEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Items&gt;
        ///  &lt;Item offset=&quot;0&quot; type=&quot;None&quot; subtype=&quot;None&quot;&gt;Nothing&lt;/Item&gt;
        ///  &lt;Item offset=&quot;1&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Dagger&lt;/Item&gt;
        ///  &lt;Item offset=&quot;2&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Mythril Knife&lt;/Item&gt;
        ///  &lt;Item offset=&quot;3&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Blind Knife&lt;/Item&gt;
        ///  &lt;Item offset=&quot;4&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Mage Masher&lt;/Item&gt;
        ///  &lt;Item offset=&quot;5&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Platinum Dagger&lt;/Item&gt;
        ///  &lt;Item offset=&quot;6&quot; type=&quot;Hand&quot; subtype=&quot;Knife&quot;&gt;Main Gauche&lt;/Item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
    }
}
