//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PSXResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PSXResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.Properties.PSXResources", typeof(PSXResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        internal static byte[] AbilitiesBin {
            get {
                object obj = ResourceManager.GetObject("AbilitiesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ActionEventsBin {
            get {
                object obj = ResourceManager.GetObject("ActionEventsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InflictStatusesBin {
            get {
                object obj = ResourceManager.GetObject("InflictStatusesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemAttributes {
            get {
                return ResourceManager.GetString("ItemAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 27, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without ev [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        internal static byte[] JobLevelsBin {
            get {
                object obj = ResourceManager.GetObject("JobLevelsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        internal static byte[] JobsBin {
            get {
                object obj = ResourceManager.GetObject("JobsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MonsterSkillsBin {
            get {
                object obj = ResourceManager.GetObject("MonsterSkillsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OldItemAttributesBin {
            get {
                object obj = ResourceManager.GetObject("OldItemAttributesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OldItemsBin {
            get {
                object obj = ResourceManager.GetObject("OldItemsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PoachProbabilitiesBin {
            get {
                object obj = ResourceManager.GetObject("PoachProbabilitiesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillSets {
            get {
                return ResourceManager.GetString("SkillSets", resourceCulture);
            }
        }
        
        internal static byte[] SkillSetsBin {
            get {
                object obj = ResourceManager.GetObject("SkillSetsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StatusAttributesBin {
            get {
                object obj = ResourceManager.GetObject("StatusAttributesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
