//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Abilities {
            get {
                object obj = ResourceManager.GetObject("Abilities", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AbilitiesBin {
            get {
                object obj = ResourceManager.GetObject("AbilitiesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AbilitiesEffects {
            get {
                object obj = ResourceManager.GetObject("AbilitiesEffects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AbilitiesStrings {
            get {
                object obj = ResourceManager.GetObject("AbilitiesStrings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AbilityEffectsBin {
            get {
                object obj = ResourceManager.GetObject("AbilityEffectsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AbilityFormulas {
            get {
                object obj = ResourceManager.GetObject("AbilityFormulas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ActionEventsBin {
            get {
                object obj = ResourceManager.GetObject("ActionEventsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ENTD1 {
            get {
                object obj = ResourceManager.GetObject("ENTD1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ENTD2 {
            get {
                object obj = ResourceManager.GetObject("ENTD2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ENTD3 {
            get {
                object obj = ResourceManager.GetObject("ENTD3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ENTD4 {
            get {
                object obj = ResourceManager.GetObject("ENTD4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ENTD5 {
            get {
                object obj = ResourceManager.GetObject("ENTD5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EventNames {
            get {
                object obj = ResourceManager.GetObject("EventNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FFTPackFiles {
            get {
                object obj = ResourceManager.GetObject("FFTPackFiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FontBin {
            get {
                object obj = ResourceManager.GetObject("FontBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FontWidthsBin {
            get {
                object obj = ResourceManager.GetObject("FontWidthsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] InflictStatusesBin {
            get {
                object obj = ResourceManager.GetObject("InflictStatusesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ItemAttributes {
            get {
                object obj = ResourceManager.GetObject("ItemAttributes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Items {
            get {
                object obj = ResourceManager.GetObject("Items", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ItemsStrings {
            get {
                object obj = ResourceManager.GetObject("ItemsStrings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JobLevelsBin {
            get {
                object obj = ResourceManager.GetObject("JobLevelsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Jobs {
            get {
                object obj = ResourceManager.GetObject("Jobs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JobsBin {
            get {
                object obj = ResourceManager.GetObject("JobsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MonsterSkillsBin {
            get {
                object obj = ResourceManager.GetObject("MonsterSkillsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NewItemAttributesBin {
            get {
                object obj = ResourceManager.GetObject("NewItemAttributesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NewItemsBin {
            get {
                object obj = ResourceManager.GetObject("NewItemsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OldItemAttributesBin {
            get {
                object obj = ResourceManager.GetObject("OldItemAttributesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OldItemsBin {
            get {
                object obj = ResourceManager.GetObject("OldItemsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] PoachProbabilitiesBin {
            get {
                object obj = ResourceManager.GetObject("PoachProbabilitiesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SkillSets {
            get {
                object obj = ResourceManager.GetObject("SkillSets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SkillSetsBin {
            get {
                object obj = ResourceManager.GetObject("SkillSetsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpecialNames {
            get {
                object obj = ResourceManager.GetObject("SpecialNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SpriteSets {
            get {
                object obj = ResourceManager.GetObject("SpriteSets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StatusAttributesBin {
            get {
                object obj = ResourceManager.GetObject("StatusAttributesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] StatusNames {
            get {
                object obj = ResourceManager.GetObject("StatusNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
