//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Abilities {
            get {
                return ResourceManager.GetString("Abilities", resourceCulture);
            }
        }
        
        internal static byte[] AbilitiesBin {
            get {
                object obj = ResourceManager.GetObject("AbilitiesBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;!--
        ///    Copyright 2007, Joe Davidson &lt;joedavidson@gmail.com&gt;
        ///
        ///    This file is part of FFTPatcher.
        ///
        ///    LionEditor is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    LionEditor is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Jobs&gt;
        ///  &lt;Job offset=&quot;00&quot; name=&quot;Blank&quot;/&gt;
        ///  &lt;Job offset=&quot;01&quot; name=&quot;Squire&quot;/&gt;
        ///  &lt;Job offset=&quot;02&quot; name=&quot;Squire&quot;/&gt;
        ///  &lt;Job offset=&quot;03&quot; name=&quot;Squire&quot;/&gt;
        ///  &lt;Job offset=&quot;04&quot; name=&quot;Squire&quot;/&gt;
        ///  &lt;Job offset=&quot;05&quot; name=&quot;Holy Knight&quot;/&gt;
        ///  &lt;Job offset=&quot;06&quot; name=&quot;Ark Knight&quot;/&gt;
        ///  &lt;Job offset=&quot;07&quot; name=&quot;Squire&quot;/&gt;
        ///  &lt;Job offset=&quot;08&quot; name=&quot;Ark Knight&quot;/&gt;
        ///  &lt;Job offset=&quot;09&quot; name=&quot;Rune Knight&quot;/&gt;
        ///  &lt;Job offset=&quot;0A&quot; name=&quot;Duke&quot;/&gt;
        ///  &lt;Job offset=&quot;0B&quot; name=&quot;Duke&quot;/&gt;
        ///  &lt;Job offset=&quot;0C&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        internal static byte[] JobsBin {
            get {
                object obj = ResourceManager.GetObject("JobsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SkillSets&gt;
        ///  &lt;SkillSet byte=&quot;00&quot;&gt;&amp;lt;Nothing&amp;gt;&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;01&quot;&gt;Attack&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;02&quot;&gt;Defend&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;03&quot;&gt;Reequip&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;04&quot;&gt;Flee&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;05&quot;&gt;Fundaments&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;06&quot;&gt;Items&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;07&quot;&gt;Arts of War&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;08&quot;&gt;Aim&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;09&quot;&gt;Martial Arts&lt;/SkillSet&gt;
        ///  &lt;SkillSet byte=&quot;0A&quot;&gt;White M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkillSets {
            get {
                return ResourceManager.GetString("SkillSets", resourceCulture);
            }
        }
        
        internal static byte[] SkillSetsBin {
            get {
                object obj = ResourceManager.GetObject("SkillSetsBin", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
