//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatcherTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatcherTests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _10M {
            get {
                object obj = ResourceManager.GetObject("_10M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _10W {
            get {
                object obj = ResourceManager.GetObject("_10W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20M {
            get {
                object obj = ResourceManager.GetObject("_20M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20W {
            get {
                object obj = ResourceManager.GetObject("_20W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _40M {
            get {
                object obj = ResourceManager.GetObject("_40M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _40W {
            get {
                object obj = ResourceManager.GetObject("_40W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _60M {
            get {
                object obj = ResourceManager.GetObject("_60M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _60W {
            get {
                object obj = ResourceManager.GetObject("_60W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ADORA {
            get {
                object obj = ResourceManager.GetObject("ADORA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AGURI {
            get {
                object obj = ResourceManager.GetObject("AGURI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AJORA {
            get {
                object obj = ResourceManager.GetObject("AJORA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Aliste {
            get {
                object obj = ResourceManager.GetObject("Aliste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARLI {
            get {
                object obj = ResourceManager.GetObject("ARLI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARU {
            get {
                object obj = ResourceManager.GetObject("ARU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUFU {
            get {
                object obj = ResourceManager.GetObject("ARUFU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUMA {
            get {
                object obj = ResourceManager.GetObject("ARUMA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUTE {
            get {
                object obj = ResourceManager.GetObject("ARUTE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Balthier {
            get {
                object obj = ResourceManager.GetObject("Balthier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARITEN {
            get {
                object obj = ResourceManager.GetObject("BARITEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARU {
            get {
                object obj = ResourceManager.GetObject("BARU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARUNA {
            get {
                object obj = ResourceManager.GetObject("BARUNA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BEHI {
            get {
                object obj = ResourceManager.GetObject("BEHI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BEIO {
            get {
                object obj = ResourceManager.GetObject("BEIO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BIBUROS {
            get {
                object obj = ResourceManager.GetObject("BIBUROS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BOM {
            get {
                object obj = ResourceManager.GetObject("BOM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BremondtDarkDragon {
            get {
                object obj = ResourceManager.GetObject("BremondtDarkDragon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BremondtHuman {
            get {
                object obj = ResourceManager.GetObject("BremondtHuman", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLOUD {
            get {
                object obj = ResourceManager.GetObject("CLOUD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOKO {
            get {
                object obj = ResourceManager.GetObject("CYOKO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON1 {
            get {
                object obj = ResourceManager.GetObject("CYOMON1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON2 {
            get {
                object obj = ResourceManager.GetObject("CYOMON2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON3 {
            get {
                object obj = ResourceManager.GetObject("CYOMON3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON4 {
            get {
                object obj = ResourceManager.GetObject("CYOMON4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DAISU {
            get {
                object obj = ResourceManager.GetObject("DAISU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DAMI {
            get {
                object obj = ResourceManager.GetObject("DAMI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DeathKnightArgath {
            get {
                object obj = ResourceManager.GetObject("DeathKnightArgath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DEMON {
            get {
                object obj = ResourceManager.GetObject("DEMON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY {
            get {
                object obj = ResourceManager.GetObject("DILY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY2 {
            get {
                object obj = ResourceManager.GetObject("DILY2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY3 {
            get {
                object obj = ResourceManager.GetObject("DILY3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA {
            get {
                object obj = ResourceManager.GetObject("DORA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA1 {
            get {
                object obj = ResourceManager.GetObject("DORA1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA2 {
            get {
                object obj = ResourceManager.GetObject("DORA2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ERU {
            get {
                object obj = ResourceManager.GetObject("ERU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FemaleDarkKnight {
            get {
                object obj = ResourceManager.GetObject("FemaleDarkKnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FemaleOnionKnight {
            get {
                object obj = ResourceManager.GetObject("FemaleOnionKnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FURAIA {
            get {
                object obj = ResourceManager.GetObject("FURAIA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FUSUI_M {
            get {
                object obj = ResourceManager.GetObject("FUSUI_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FUSUI_W {
            get {
                object obj = ResourceManager.GetObject("FUSUI_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FYUNE {
            get {
                object obj = ResourceManager.GetObject("FYUNE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GANDO {
            get {
                object obj = ResourceManager.GetObject("GANDO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GARU {
            get {
                object obj = ResourceManager.GetObject("GARU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GIN_M {
            get {
                object obj = ResourceManager.GetObject("GIN_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GOB {
            get {
                object obj = ResourceManager.GetObject("GOB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GORU {
            get {
                object obj = ResourceManager.GetObject("GORU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GYUMU {
            get {
                object obj = ResourceManager.GetObject("GYUMU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H61 {
            get {
                object obj = ResourceManager.GetObject("H61", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H75 {
            get {
                object obj = ResourceManager.GetObject("H75", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H76 {
            get {
                object obj = ResourceManager.GetObject("H76", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H77 {
            get {
                object obj = ResourceManager.GetObject("H77", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H78 {
            get {
                object obj = ResourceManager.GetObject("H78", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H79 {
            get {
                object obj = ResourceManager.GetObject("H79", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H80 {
            get {
                object obj = ResourceManager.GetObject("H80", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H81 {
            get {
                object obj = ResourceManager.GetObject("H81", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H82 {
            get {
                object obj = ResourceManager.GetObject("H82", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H83 {
            get {
                object obj = ResourceManager.GetObject("H83", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H85 {
            get {
                object obj = ResourceManager.GetObject("H85", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HASYU {
            get {
                object obj = ResourceManager.GetObject("HASYU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HEBI {
            get {
                object obj = ResourceManager.GetObject("HEBI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HIME {
            get {
                object obj = ResourceManager.GetObject("HIME", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HYOU {
            get {
                object obj = ResourceManager.GetObject("HYOU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IKA {
            get {
                object obj = ResourceManager.GetObject("IKA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ITEM_M {
            get {
                object obj = ResourceManager.GetObject("ITEM_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ITEM_W {
            get {
                object obj = ResourceManager.GetObject("ITEM_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANBA {
            get {
                object obj = ResourceManager.GetObject("KANBA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANZEN {
            get {
                object obj = ResourceManager.GetObject("KANZEN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KI {
            get {
                object obj = ResourceManager.GetObject("KI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KNIGHT_M {
            get {
                object obj = ResourceManager.GetObject("KNIGHT_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KNIGHT_W {
            get {
                object obj = ResourceManager.GetObject("KNIGHT_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KURO_M {
            get {
                object obj = ResourceManager.GetObject("KURO_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KURO_W {
            get {
                object obj = ResourceManager.GetObject("KURO_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KYUKU {
            get {
                object obj = ResourceManager.GetObject("KYUKU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LEDY {
            get {
                object obj = ResourceManager.GetObject("LEDY", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Luso {
            get {
                object obj = ResourceManager.GetObject("Luso", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MaleDarkKnight {
            get {
                object obj = ResourceManager.GetObject("MaleDarkKnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MaleOnionKnight {
            get {
                object obj = ResourceManager.GetObject("MaleOnionKnight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MARA {
            get {
                object obj = ResourceManager.GetObject("MARA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINA_M {
            get {
                object obj = ResourceManager.GetObject("MINA_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINA_W {
            get {
                object obj = ResourceManager.GetObject("MINA_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINOTA {
            get {
                object obj = ResourceManager.GetObject("MINOTA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MOL {
            get {
                object obj = ResourceManager.GetObject("MOL", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONK_M {
            get {
                object obj = ResourceManager.GetObject("MONK_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONK_W {
            get {
                object obj = ResourceManager.GetObject("MONK_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONO_M {
            get {
                object obj = ResourceManager.GetObject("MONO_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONO_W {
            get {
                object obj = ResourceManager.GetObject("MONO_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MUSU {
            get {
                object obj = ResourceManager.GetObject("MUSU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NINJA_M {
            get {
                object obj = ResourceManager.GetObject("NINJA_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NINJA_W {
            get {
                object obj = ResourceManager.GetObject("NINJA_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ODORI_W {
            get {
                object obj = ResourceManager.GetObject("ODORI_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ONMYO_M {
            get {
                object obj = ResourceManager.GetObject("ONMYO_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ONMYO_W {
            get {
                object obj = ResourceManager.GetObject("ONMYO_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ORAN {
            get {
                object obj = ResourceManager.GetObject("ORAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ORU {
            get {
                object obj = ResourceManager.GetObject("ORU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OTHER {
            get {
                object obj = ResourceManager.GetObject("OTHER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAFA {
            get {
                object obj = ResourceManager.GetObject("RAFA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAGU {
            get {
                object obj = ResourceManager.GetObject("RAGU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA {
            get {
                object obj = ResourceManager.GetObject("RAMUZA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA2 {
            get {
                object obj = ResourceManager.GetObject("RAMUZA2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA3 {
            get {
                object obj = ResourceManager.GetObject("RAMUZA3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] REZE {
            get {
                object obj = ResourceManager.GetObject("REZE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] REZE_D {
            get {
                object obj = ResourceManager.GetObject("REZE_D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RUDO {
            get {
                object obj = ResourceManager.GetObject("RUDO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RYU_M {
            get {
                object obj = ResourceManager.GetObject("RYU_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RYU_W {
            get {
                object obj = ResourceManager.GetObject("RYU_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAMU_M {
            get {
                object obj = ResourceManager.GetObject("SAMU_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAMU_W {
            get {
                object obj = ResourceManager.GetObject("SAMU_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAN_M {
            get {
                object obj = ResourceManager.GetObject("SAN_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAN_W {
            get {
                object obj = ResourceManager.GetObject("SAN_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SERIA {
            get {
                object obj = ResourceManager.GetObject("SERIA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIMON {
            get {
                object obj = ResourceManager.GetObject("SIMON", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIRO_M {
            get {
                object obj = ResourceManager.GetObject("SIRO_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIRO_W {
            get {
                object obj = ResourceManager.GetObject("SIRO_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SOURYO {
            get {
                object obj = ResourceManager.GetObject("SOURYO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SUKERU {
            get {
                object obj = ResourceManager.GetObject("SUKERU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SwordInStone {
            get {
                object obj = ResourceManager.GetObject("SwordInStone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SYOU_M {
            get {
                object obj = ResourceManager.GetObject("SYOU_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SYOU_W {
            get {
                object obj = ResourceManager.GetObject("SYOU_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TETSU {
            get {
                object obj = ResourceManager.GetObject("TETSU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] THIEF_M {
            get {
                object obj = ResourceManager.GetObject("THIEF_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] THIEF_W {
            get {
                object obj = ResourceManager.GetObject("THIEF_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TOKI_M {
            get {
                object obj = ResourceManager.GetObject("TOKI_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TOKI_W {
            get {
                object obj = ResourceManager.GetObject("TOKI_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TORI {
            get {
                object obj = ResourceManager.GetObject("TORI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] URI {
            get {
                object obj = ResourceManager.GetObject("URI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VERI {
            get {
                object obj = ResourceManager.GetObject("VERI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VORU {
            get {
                object obj = ResourceManager.GetObject("VORU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WAJU_M {
            get {
                object obj = ResourceManager.GetObject("WAJU_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WAJU_W {
            get {
                object obj = ResourceManager.GetObject("WAJU_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WEP {
            get {
                object obj = ResourceManager.GetObject("WEP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WIGU {
            get {
                object obj = ResourceManager.GetObject("WIGU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUMI_M {
            get {
                object obj = ResourceManager.GetObject("YUMI_M", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUMI_W {
            get {
                object obj = ResourceManager.GetObject("YUMI_W", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUREI {
            get {
                object obj = ResourceManager.GetObject("YUREI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARU {
            get {
                object obj = ResourceManager.GetObject("ZARU", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARU2 {
            get {
                object obj = ResourceManager.GetObject("ZARU2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARUE {
            get {
                object obj = ResourceManager.GetObject("ZARUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARUMOU {
            get {
                object obj = ResourceManager.GetObject("ZARUMOU", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
