//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.SpriteEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.SpriteEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] _10M_SPR {
            get {
                object obj = ResourceManager.GetObject("_10M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _10W_SPR {
            get {
                object obj = ResourceManager.GetObject("_10W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20M_SPR {
            get {
                object obj = ResourceManager.GetObject("_20M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _20W_SPR {
            get {
                object obj = ResourceManager.GetObject("_20W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _40M_SPR {
            get {
                object obj = ResourceManager.GetObject("_40M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _40W_SPR {
            get {
                object obj = ResourceManager.GetObject("_40W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _60M_SPR {
            get {
                object obj = ResourceManager.GetObject("_60M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] _60W_SPR {
            get {
                object obj = ResourceManager.GetObject("_60W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ADORA_SPR {
            get {
                object obj = ResourceManager.GetObject("ADORA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AGURI_SPR {
            get {
                object obj = ResourceManager.GetObject("AGURI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] AJORA_SPR {
            get {
                object obj = ResourceManager.GetObject("AJORA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARLI_SPR {
            get {
                object obj = ResourceManager.GetObject("ARLI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARLI2_SP2 {
            get {
                object obj = ResourceManager.GetObject("ARLI2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARU_SPR {
            get {
                object obj = ResourceManager.GetObject("ARU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUFU_SPR {
            get {
                object obj = ResourceManager.GetObject("ARUFU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUMA_SPR {
            get {
                object obj = ResourceManager.GetObject("ARUMA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUTE_SHP {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ARUTE_SPR {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARITEN_SPR {
            get {
                object obj = ResourceManager.GetObject("BARITEN_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARU_SPR {
            get {
                object obj = ResourceManager.GetObject("BARU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BARUNA_SPR {
            get {
                object obj = ResourceManager.GetObject("BARUNA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BEHI_SPR {
            get {
                object obj = ResourceManager.GetObject("BEHI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BEHI2_SP2 {
            get {
                object obj = ResourceManager.GetObject("BEHI2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BEIO_SPR {
            get {
                object obj = ResourceManager.GetObject("BEIO_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BIBU2_SP2 {
            get {
                object obj = ResourceManager.GetObject("BIBU2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BIBUROS_SPR {
            get {
                object obj = ResourceManager.GetObject("BIBUROS_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BOM_SPR {
            get {
                object obj = ResourceManager.GetObject("BOM_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BOM2_SP2 {
            get {
                object obj = ResourceManager.GetObject("BOM2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CLOUD_SPR {
            get {
                object obj = ResourceManager.GetObject("CLOUD_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOKO_SHP {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOKO_SPR {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON1_SPR {
            get {
                object obj = ResourceManager.GetObject("CYOMON1_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON2_SPR {
            get {
                object obj = ResourceManager.GetObject("CYOMON2_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON3_SPR {
            get {
                object obj = ResourceManager.GetObject("CYOMON3_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOMON4_SPR {
            get {
                object obj = ResourceManager.GetObject("CYOMON4_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DAISU_SPR {
            get {
                object obj = ResourceManager.GetObject("DAISU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DEMON_SPR {
            get {
                object obj = ResourceManager.GetObject("DEMON_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DEMON2_SP2 {
            get {
                object obj = ResourceManager.GetObject("DEMON2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY_SPR {
            get {
                object obj = ResourceManager.GetObject("DILY_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY2_SPR {
            get {
                object obj = ResourceManager.GetObject("DILY2_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DILY3_SPR {
            get {
                object obj = ResourceManager.GetObject("DILY3_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA_SPR {
            get {
                object obj = ResourceManager.GetObject("DORA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA1_SPR {
            get {
                object obj = ResourceManager.GetObject("DORA1_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA2_SPR {
            get {
                object obj = ResourceManager.GetObject("DORA2_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DORA22_SP2 {
            get {
                object obj = ResourceManager.GetObject("DORA22_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EFF1_SHP {
            get {
                object obj = ResourceManager.GetObject("EFF1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] EFF2_SHP {
            get {
                object obj = ResourceManager.GetObject("EFF2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ERU_SPR {
            get {
                object obj = ResourceManager.GetObject("ERU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FURAIA_SPR {
            get {
                object obj = ResourceManager.GetObject("FURAIA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FUSUI_M_SPR {
            get {
                object obj = ResourceManager.GetObject("FUSUI_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FUSUI_W_SPR {
            get {
                object obj = ResourceManager.GetObject("FUSUI_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] FYUNE_SPR {
            get {
                object obj = ResourceManager.GetObject("FYUNE_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GANDO_SPR {
            get {
                object obj = ResourceManager.GetObject("GANDO_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GARU_SPR {
            get {
                object obj = ResourceManager.GetObject("GARU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GIN_M_SPR {
            get {
                object obj = ResourceManager.GetObject("GIN_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GOB_SPR {
            get {
                object obj = ResourceManager.GetObject("GOB_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GORU_SPR {
            get {
                object obj = ResourceManager.GetObject("GORU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GYUMU_SPR {
            get {
                object obj = ResourceManager.GetObject("GYUMU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H61_SPR {
            get {
                object obj = ResourceManager.GetObject("H61_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H75_SPR {
            get {
                object obj = ResourceManager.GetObject("H75_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H76_SPR {
            get {
                object obj = ResourceManager.GetObject("H76_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H77_SPR {
            get {
                object obj = ResourceManager.GetObject("H77_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H78_SPR {
            get {
                object obj = ResourceManager.GetObject("H78_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H79_SPR {
            get {
                object obj = ResourceManager.GetObject("H79_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H80_SPR {
            get {
                object obj = ResourceManager.GetObject("H80_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H81_SPR {
            get {
                object obj = ResourceManager.GetObject("H81_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H82_SPR {
            get {
                object obj = ResourceManager.GetObject("H82_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H83_SPR {
            get {
                object obj = ResourceManager.GetObject("H83_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] H85_SPR {
            get {
                object obj = ResourceManager.GetObject("H85_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HASYU_SPR {
            get {
                object obj = ResourceManager.GetObject("HASYU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HEBI_SPR {
            get {
                object obj = ResourceManager.GetObject("HEBI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HIME_SPR {
            get {
                object obj = ResourceManager.GetObject("HIME_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HYOU_SPR {
            get {
                object obj = ResourceManager.GetObject("HYOU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] HYOU2_SP2 {
            get {
                object obj = ResourceManager.GetObject("HYOU2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IKA_SPR {
            get {
                object obj = ResourceManager.GetObject("IKA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IRON2_SP2 {
            get {
                object obj = ResourceManager.GetObject("IRON2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IRON3_SP2 {
            get {
                object obj = ResourceManager.GetObject("IRON3_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IRON4_SP2 {
            get {
                object obj = ResourceManager.GetObject("IRON4_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] IRON5_SP2 {
            get {
                object obj = ResourceManager.GetObject("IRON5_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ITEM_M_SPR {
            get {
                object obj = ResourceManager.GetObject("ITEM_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ITEM_W_SPR {
            get {
                object obj = ResourceManager.GetObject("ITEM_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANBA_SPR {
            get {
                object obj = ResourceManager.GetObject("KANBA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANZEN_SHP {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANZEN_SPR {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KI_SPR {
            get {
                object obj = ResourceManager.GetObject("KI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KNIGHT_M_SPR {
            get {
                object obj = ResourceManager.GetObject("KNIGHT_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KNIGHT_W_SPR {
            get {
                object obj = ResourceManager.GetObject("KNIGHT_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KURO_M_SPR {
            get {
                object obj = ResourceManager.GetObject("KURO_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KURO_W_SPR {
            get {
                object obj = ResourceManager.GetObject("KURO_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KYUKU_SPR {
            get {
                object obj = ResourceManager.GetObject("KYUKU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] LEDY_SPR {
            get {
                object obj = ResourceManager.GetObject("LEDY_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MARA_SPR {
            get {
                object obj = ResourceManager.GetObject("MARA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINA_M_SPR {
            get {
                object obj = ResourceManager.GetObject("MINA_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINA_W_SPR {
            get {
                object obj = ResourceManager.GetObject("MINA_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINOTA_SPR {
            get {
                object obj = ResourceManager.GetObject("MINOTA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MINOTA2_SP2 {
            get {
                object obj = ResourceManager.GetObject("MINOTA2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MOL_SPR {
            get {
                object obj = ResourceManager.GetObject("MOL_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MOL2_SP2 {
            get {
                object obj = ResourceManager.GetObject("MOL2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MON_SHP {
            get {
                object obj = ResourceManager.GetObject("MON_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONK_M_SPR {
            get {
                object obj = ResourceManager.GetObject("MONK_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONK_W_SPR {
            get {
                object obj = ResourceManager.GetObject("MONK_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONO_M_SPR {
            get {
                object obj = ResourceManager.GetObject("MONO_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MONO_W_SPR {
            get {
                object obj = ResourceManager.GetObject("MONO_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] MUSU_SPR {
            get {
                object obj = ResourceManager.GetObject("MUSU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NINJA_M_SPR {
            get {
                object obj = ResourceManager.GetObject("NINJA_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] NINJA_W_SPR {
            get {
                object obj = ResourceManager.GetObject("NINJA_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ODORI_W_SPR {
            get {
                object obj = ResourceManager.GetObject("ODORI_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ONMYO_M_SPR {
            get {
                object obj = ResourceManager.GetObject("ONMYO_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ONMYO_W_SPR {
            get {
                object obj = ResourceManager.GetObject("ONMYO_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ORAN_SPR {
            get {
                object obj = ResourceManager.GetObject("ORAN_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ORU_SPR {
            get {
                object obj = ResourceManager.GetObject("ORU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OTHER_SHP {
            get {
                object obj = ResourceManager.GetObject("OTHER_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAFA_SPR {
            get {
                object obj = ResourceManager.GetObject("RAFA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAGU_SPR {
            get {
                object obj = ResourceManager.GetObject("RAGU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA_SPR {
            get {
                object obj = ResourceManager.GetObject("RAMUZA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA2_SPR {
            get {
                object obj = ResourceManager.GetObject("RAMUZA2_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RAMUZA3_SPR {
            get {
                object obj = ResourceManager.GetObject("RAMUZA3_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] REZE_D_SPR {
            get {
                object obj = ResourceManager.GetObject("REZE_D_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] REZE_SPR {
            get {
                object obj = ResourceManager.GetObject("REZE_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RUDO_SPR {
            get {
                object obj = ResourceManager.GetObject("RUDO_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RYU_M_SPR {
            get {
                object obj = ResourceManager.GetObject("RYU_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RYU_W_SPR {
            get {
                object obj = ResourceManager.GetObject("RYU_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAMU_M_SPR {
            get {
                object obj = ResourceManager.GetObject("SAMU_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAMU_W_SPR {
            get {
                object obj = ResourceManager.GetObject("SAMU_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAN_M_SPR {
            get {
                object obj = ResourceManager.GetObject("SAN_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAN_W_SPR {
            get {
                object obj = ResourceManager.GetObject("SAN_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SERIA_SPR {
            get {
                object obj = ResourceManager.GetObject("SERIA_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIMON_SPR {
            get {
                object obj = ResourceManager.GetObject("SIMON_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIRO_M_SPR {
            get {
                object obj = ResourceManager.GetObject("SIRO_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SIRO_W_SPR {
            get {
                object obj = ResourceManager.GetObject("SIRO_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SOURYO_SPR {
            get {
                object obj = ResourceManager.GetObject("SOURYO_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SUKERU_SPR {
            get {
                object obj = ResourceManager.GetObject("SUKERU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SYOU_M_SPR {
            get {
                object obj = ResourceManager.GetObject("SYOU_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SYOU_W_SPR {
            get {
                object obj = ResourceManager.GetObject("SYOU_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TETSU_SPR {
            get {
                object obj = ResourceManager.GetObject("TETSU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] THIEF_M_SPR {
            get {
                object obj = ResourceManager.GetObject("THIEF_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] THIEF_W_SPR {
            get {
                object obj = ResourceManager.GetObject("THIEF_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TOKI_M_SPR {
            get {
                object obj = ResourceManager.GetObject("TOKI_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TOKI_W_SPR {
            get {
                object obj = ResourceManager.GetObject("TOKI_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TORI_SPR {
            get {
                object obj = ResourceManager.GetObject("TORI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TORI2_SP2 {
            get {
                object obj = ResourceManager.GetObject("TORI2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TYPE1_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TYPE2_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] URI_SPR {
            get {
                object obj = ResourceManager.GetObject("URI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] URI2_SP2 {
            get {
                object obj = ResourceManager.GetObject("URI2_SP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VERI_SPR {
            get {
                object obj = ResourceManager.GetObject("VERI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] VORU_SPR {
            get {
                object obj = ResourceManager.GetObject("VORU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WAJU_M_SPR {
            get {
                object obj = ResourceManager.GetObject("WAJU_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WAJU_W_SPR {
            get {
                object obj = ResourceManager.GetObject("WAJU_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WEP1_SHP {
            get {
                object obj = ResourceManager.GetObject("WEP1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WEP2_SHP {
            get {
                object obj = ResourceManager.GetObject("WEP2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WIGU_SPR {
            get {
                object obj = ResourceManager.GetObject("WIGU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUMI_M_SPR {
            get {
                object obj = ResourceManager.GetObject("YUMI_M_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUMI_W_SPR {
            get {
                object obj = ResourceManager.GetObject("YUMI_W_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] YUREI_SPR {
            get {
                object obj = ResourceManager.GetObject("YUREI_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARU_SPR {
            get {
                object obj = ResourceManager.GetObject("ZARU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARU2_SPR {
            get {
                object obj = ResourceManager.GetObject("ZARU2_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARUE_SPR {
            get {
                object obj = ResourceManager.GetObject("ZARUE_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ZARUMOU_SPR {
            get {
                object obj = ResourceManager.GetObject("ZARUMOU_SPR", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
