//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.SpriteEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.SpriteEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ARUTE_SHP {
            get {
                object obj = ResourceManager.GetObject("ARUTE_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] CYOKO_SHP {
            get {
                object obj = ResourceManager.GetObject("CYOKO_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] KANZEN_SHP {
            get {
                object obj = ResourceManager.GetObject("KANZEN_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PspFiles&gt;
        ///  &lt;FFTPatcher.SpriteEditor.MonsterSprite&gt;
        ///    &lt;Sprite name=&quot;ARLI&quot;&gt;
        ///      &lt;Files&gt;
        ///        &lt;File name=&quot;ARLI.SPR&quot; enum=&quot;BATTLE_ARLI_SPR&quot; original_size=&quot;41475&quot;/&gt;
        ///        &lt;File name=&quot;ARLI2.SP2&quot; enum=&quot;BATTLE_ARLI2_SP2&quot; original_size=&quot;32768&quot;/&gt;
        ///      &lt;/Files&gt;
        ///    &lt;/Sprite&gt;
        ///    &lt;Sprite name=&quot;BEHI&quot;&gt;
        ///      &lt;Files&gt;
        ///        &lt;File name=&quot;BEHI.SPR&quot; enum=&quot;BATTLE_BEHI_SPR&quot; original_size=&quot;46393&quot;/&gt;
        ///        &lt;File name=&quot;BEHI2.SP2&quot; enum=&quot;BATTLE_BEHI2_SP2&quot; original_siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSPFiles {
            get {
                return ResourceManager.GetString("PSPFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PsxFiles&gt;
        ///  &lt;FFTPatcher.SpriteEditor.MonsterSprite&gt;
        ///    &lt;Sprite name=&quot;ARLI&quot;&gt;
        ///      &lt;Files&gt;
        ///        &lt;File name=&quot;ARLI.SPR&quot; enum=&quot;BATTLE_ARLI_SPR&quot; original_size=&quot;41475&quot;/&gt;
        ///        &lt;File name=&quot;ARLI2.SP2&quot; enum=&quot;BATTLE_ARLI2_SP2&quot; original_size=&quot;32768&quot;/&gt;
        ///      &lt;/Files&gt;
        ///    &lt;/Sprite&gt;
        ///    &lt;Sprite name=&quot;BEHI&quot;&gt;
        ///      &lt;Files&gt;
        ///        &lt;File name=&quot;BEHI.SPR&quot; enum=&quot;BATTLE_BEHI_SPR&quot; original_size=&quot;46393&quot;/&gt;
        ///        &lt;File name=&quot;BEHI2.SP2&quot; enum=&quot;BATTLE_BEHI2_SP2&quot; original_siz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PSXFiles {
            get {
                return ResourceManager.GetString("PSXFiles", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon sprite {
            get {
                object obj = ResourceManager.GetObject("sprite", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] TYPE1_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE1_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TYPE2_SHP {
            get {
                object obj = ResourceManager.GetObject("TYPE2_SHP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WLDFACE {
            get {
                object obj = ResourceManager.GetObject("WLDFACE", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
