//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.TextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PSXResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PSXResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.TextEditor.Properties.PSXResources", typeof(PSXResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] ATCHELP_LZW {
            get {
                object obj = ResourceManager.GetObject("ATCHELP_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ATTACK_OUT_partial {
            get {
                object obj = ResourceManager.GetObject("ATTACK_OUT_partial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] JOIN_LZW {
            get {
                object obj = ResourceManager.GetObject("JOIN_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] OPEN_LZW {
            get {
                object obj = ResourceManager.GetObject("OPEN_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SAMPLE_LZW {
            get {
                object obj = ResourceManager.GetObject("SAMPLE_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SNPLMES_BIN {
            get {
                object obj = ResourceManager.GetObject("SNPLMES_BIN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WLDHELP_LZW {
            get {
                object obj = ResourceManager.GetObject("WLDHELP_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WLDMES_BIN {
            get {
                object obj = ResourceManager.GetObject("WLDMES_BIN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] WORLD_LZW {
            get {
                object obj = ResourceManager.GetObject("WORLD_LZW", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
