//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFTPatcher.TextEditor.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFTPatcher.TextEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] EntryNames {
            get {
                object obj = ResourceManager.GetObject("EntryNames", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PSP&gt;
        ///  &lt;Files&gt;
        ///    &lt;SectionedFile&gt;
        ///      &lt;DisplayName&gt;ATCHELP.LZW&lt;/DisplayName&gt;
        ///      &lt;Guid&gt;{B66C9774-1EA0-422c-9148-B5019301EAB4}&lt;/Guid&gt;
        ///      &lt;Size&gt;129076&lt;/Size&gt;
        ///      &lt;Sectors&gt;
        ///        &lt;FFTPack index=&quot;EVENT_ATCHELP_LZW&quot; offset=&quot;0&quot;/&gt;
        ///      &lt;/Sectors&gt;
        ///      &lt;Sections count=&quot;21&quot;&gt;
        ///        &lt;Section value=&quot;0&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Section value=&quot;1&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Section value=&quot;2&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Secti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string psp {
            get {
                return ResourceManager.GetString("psp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;PSX&gt;
        ///  &lt;Files&gt;
        ///    &lt;SectionedFile&gt;
        ///      &lt;DisplayName&gt;ATCHELP.LZW&lt;/DisplayName&gt;
        ///      &lt;Guid&gt;{8BF49EAB-6D21-44c6-B63F-F6315AAEFD9B}&lt;/Guid&gt;
        ///      &lt;Size&gt;92160&lt;/Size&gt;
        ///      &lt;Sectors&gt;
        ///        &lt;Sector filename=&quot;EVENT_ATCHELP_LZW&quot; offset=&quot;0&quot;/&gt;
        ///      &lt;/Sectors&gt;
        ///      &lt;Sections count=&quot;21&quot;&gt;
        ///        &lt;Section value=&quot;0&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Section value=&quot;1&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Section value=&quot;2&quot; entries=&quot;1&quot; empty=&quot;true&quot;/&gt;
        ///        &lt;Sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string psx {
            get {
                return ResourceManager.GetString("psx", resourceCulture);
            }
        }
    }
}
